service: 'crypto-alerts'
frameworkVersion: '2'

custom:
  webpack:
    webpackConfig: './webpack.config.js'
    includeModules: true

plugins: 
    - serverless-webpack

provider: 
  name: 'aws'
  runtime: 'nodejs14.x'
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment: 
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
  lambdaHashingVersion: '20201221'

functions: 
  hello:
    handler: src/functions/hello/handler.main
    events:
      - schedule: rate(2 minutes)
    
