service: 'crypto-alerts'

frameworkVersion: '2'

custom:
  webpack:
    webpackConfig: './webpack.config.js'
    includeModules: true

plugins: 
    - serverless-webpack

provider: 
  name: 'aws'
  region: us-east-1
  runtime: 'nodejs14.x'
  deploymentBucket: crypto-alerts-build-bucket

functions: 
  main:
    handler: src/functions/main/handler.main
    events:
      - schedule: rate(10 minutes)
    
resources:
  Resources:
    AlertTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - 
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'crypto-alerts-dev-main'
